### ISSUE TITLE
call.getFileName not defined getting error on pulsar on startup.

### ISSUE THREAD

**Issue by S0ulflared** [mjrodgers/pulsar-ide-python#9]
error output: 
<img width="465" alt="Screenshot 2024-03-13 at 8 21 07 AM" src="https://github.com/mjrodgers/pulsar-ide-python/assets/97210119/287e674f-40c6-4598-8976-45e6152b5b52">
stack trace: Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=87 uv=1 armv=8 libc=glibc node=14.16.0 electron=12.2.3
    loaded from: /Users/connorwatson/.pulsar/packages/pulsar-ide-python/node_modules/zadeh
    at Function.load.resolve.load.path (/Users/connorwatson/.pulsar/packages/ide-html/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/Users/connorwatson/.pulsar/packages/ide-html/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/Users/connorwatson/.pulsar/packages/ide-html/node_modules/zadeh/index.js:1:2743)
    at Object.<anonymous> (/Users/connorwatson/.pulsar/packages/ide-html/node_modules/zadeh/index.js:4:3)
    at Module._compile (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/Applications/Pulsar.app/Contents/Resources/app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/Users/connorwatson/.pulsar/packages/pulsar-ide-python/node_modules/@savetheclocktower/atom-languageclient/build/lib/adapters/autocomplete-adapter.js:41:17)
    at Object.<anonymous> (/Users/connorwatson/.pulsar/packages/pulsar-ide-python/node_modules/@savetheclocktower/atom-languageclient/build/lib/adapters/autocomplete-adapter.js:548:3)
    at Module._compile (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/Applications/Pulsar.app/Contents/Resources/app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/Users/connorwatson/.pulsar/packages/pulsar-ide-python/node_modules/@savetheclocktower/atom-languageclient/build/lib/auto-languageclient.js:45:45)
    at Object.<anonymous> (/Users/connorwatson/.pulsar/packages/pulsar-ide-python/node_modules/@savetheclocktower/atom-languageclient/build/lib/auto-languageclient.js:1243:3)
    at Module._compile (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/Applications/Pulsar.app/Contents/Resources/app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/Users/connorwatson/.pulsar/packages/pulsar-ide-python/node_modules/@savetheclocktower/atom-languageclient/build/lib/main.js:25:47)
    at Object.<anonymous> (/Users/connorwatson/.pulsar/packages/pulsar-ide-python/node_modules/@savetheclocktower/atom-languageclient/build/lib/main.js:42:3)
    at Module._compile (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/Applications/Pulsar.app/Contents/Resources/app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:67:27)
    at Object.<anonymous> (/Users/connorwatson/.pulsar/packages/pulsar-ide-python/lib/main.js:3:32)
    at Object.<anonymous> (/Users/connorwatson/.pulsar/packages/pulsar-ide-python/lib/main.js:140:3)
    at Module._compile (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/Applications/Pulsar.app/Contents/Resources/app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/Applications/Pulsar.app/Contents/Resources/app.asar/src/native-compile-cache.js:67:27)
    at requireModule (/Applications/Pulsar.app/Contents/Resources/app.asar/src/module-utils.js:3:17)
    at Package.requireMainModule (/Applications/Pulsar.app/Contents/Resources/app.asar/src/package.js:912:27)
    at Package.activateNow (/Applications/Pulsar.app/Contents/Resources/app.asar/src/package.js:232:34)
    at /Applications/Pulsar.app/Contents/Resources/app.asar/src/package.js:1067:18
    at Function.simpleDispatch (/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/event-kit/dist/emitter.js:257:28)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Pulsar.app/Contents/Resources/app.asar/src/package-manager.js:804:34)
    at /Applications/Pulsar.app/Contents/Resources/app.asar/src/package-manager.js:733:12
    at TextEditorRegistry.updateAndMonitorEditorSettings (/Applications/Pulsar.app/Contents/Resources/app.asar/src/text-editor-registry.js:235:5)

**Comment by mjrodgers** [comment]
The first issue with `call.getFileName` is with the outdated version (`ide-python`) of the package; you seem to have both installed. Please uninstall that one and only use `pulsar-ide-python`; there should not be any installation errors with the current version.
